
# Packages
[packages]

# Required Packages
required = [
  "mesa",
  "dunst",
  "grim",
  "slurp",
  "gnome-themes-extra",
  "qt5-multimedia",
  "qt6-multimedia",
  "pipewire",
  "pipewire-alsa",
  "pipewire-audio",
  "pipewire-jack",
  "pipewire-pulse",
  "zsh",
  "networkmanager",
  "network-manager-applet",
  "bluez",
  "bluez-utils",
  "vim",
  "neovim",
  "htop",
  "kitty",
  "alacritty",
  "fastfetch",
  "exa",
  "foot",
  "yay",
  "nautilus",
  "gvfs",
  "gvfs-mtp",
  "noto-fonts",
  "noto-fonts-emoji",
  "ttf-cascadia-code-nerd",
  "ttf-cascadia-mono-nerd",
  "ttf-nerd-fonts-symbols",
  "sddm",
  "nebula-keybind-menu",
  "nebula-oh-my-zsh",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-utils",
  "xdg-user-dirs",
  "polkit-gnome",
  "wl-clipboard",
  "waybar",
  "wayland",
  "wayland-protocols",
  "qt5-wayland",
  "qt6-wayland",
  "rofi",
  "jq",
]

# Hyprland Packages
hyprland = [
  "hyprland",
  "hyprlock",
  "hyprpicker",
  "hyprpaper",
  "hypridle",
  "hyprland-guiutils",
  "hyprsunset",
  "hyprutils",
  "hyprtoolkit",
  "nebula-hypr",
  "xdg-desktop-portal-hyprland",
]

# Compositors
[selections]
compositors = ["Hyprland"]

# Web Browsers
[[selections.browsers]]
label = "Firefox"
pacman = ["firefox", "firefox-ublock-origin"]

[[selections.browsers]]
label = "Chromium"
pacman = ["chromium"]

[[selections.browsers]]
label = "Ungoogled Chromium"
yay = ["ungoogled-chromium-bin"]

[[selections.browsers]]
label = "Helium"
yay = ["helium-browser-bin"]

[[selections.browsers]]
label = "Brave"
yay = ["brave-bin"]

[[selections.browsers]]
label = "Zen Browser"
yay = ["zen-browser-bin"]

[[selections.browsers]]
label = "LibreWolf"
yay = ["librewolf-bin"]

[[selections.browsers]]
label = "Mullvad"
yay = ["mullvad-browser-bin"]

[[selections.browsers]]
label = "qutebrowser"
pacman = ["qutebrowser"]

# Terminal Emulators
[[selections.terminals]]
label = "Ghostty"
pacman = ["ghostty"]

[[selections.terminals]]
label = "Kitty"
pacman = ["kitty"]

[[selections.terminals]]
label = "Alacritty"
pacman = ["alacritty"]

# Code Editors
[[selections.editors]]
label = "Zed"
pacman = ["zed"]

[[selections.editors]]
label = "Cursor"
yay = ["cursor-bin"]

[[selections.editors]]
label = "Visual Studio Code"
yay = ["visual-studio-code-bin"]

[[selections.editors]]
label = "VSCodium"
yay = ["vscodium-bin"]

[[selections.editors]]
label = "Sublime Text 4"
yay = ["sublime-text-4"]
